<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOoRrxJ5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOoRrxJ5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOoRrxJ5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOoRrxJ5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOoRrxJ5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'OoRrxJ5',
    'container.build_id' => '715e5be0',
    'container.build_time' => 1552323501,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOoRrxJ5');
