<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSlBbgqL\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSlBbgqL/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSlBbgqL.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSlBbgqL\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSlBbgqL\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SlBbgqL',
    'container.build_id' => '7ae0a62e',
    'container.build_time' => 1552228688,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSlBbgqL');
